package com.webitel.chat.sdk

/**
 * Represents message content received from the server.
 *
 * A message may include text, attachments, interactive elements (keyboard),
 * or a combination of these.
 *
 * Some fields (e.g. keyboard, system events) are server-driven and may not be
 * available when sending messages from the client.
 */
sealed class MessageContent {

    /** Plain text message. */
    data class Text(
        val text: String
    ) : MessageContent()


    /** Message containing only attachments. */
    data class Attachments(
        val attachments: List<MessageAttachment>
    ) : MessageContent()


    /**
     * Message containing only an interactive keyboard.
     *
     * Used for server-driven UI such as bots or quick replies.
     */
    data class KeyboardOnly(
        val keyboard: ChatKeyboard
    ) : MessageContent()


    /**
     * Message with combined content.
     *
     * Supports common combinations:
     * - text + attachments
     * - text + keyboard
     * - attachments + keyboard
     * - text + attachments + keyboard
     *
     * The keyboard field is typically populated by the server.
     */
    data class Composite(
        val text: String? = null,
        val attachments: List<MessageAttachment> = emptyList(),
        val keyboard: ChatKeyboard? = null
    ) : MessageContent()


    /** Contact information shared in a message. */
    data class Contact(
        val name: String,
        val phone: String?,
        val email: String?
    ) : MessageContent()


    /** Geographic location shared in a message. */
    data class Location(
        val name: String,
        val address: String,
        val latitude: Double,
        val longitude: Double
    ) : MessageContent()


    /**
     * System message generated by backend or client logic.
     *
     * Represents events such as user join/leave, status updates, etc.
     */
    data class System(
        val type: String,
        val text: String
    ) : MessageContent()
}


/**
 * Represents message content that can be sent from the client.
 *
 * This is a restricted subset of [MessageContent].
 * The server may transform or extend the message after it is sent.
 */
sealed class SendContent {

    /** Plain text message. */
    data class Text(
        val text: String
    ) : SendContent()


    /**
     * Message containing one or more file attachments.
     *
     * Attachments may reference:
     * - previously uploaded files
     * - external URLs
     *
     * Example:
     * ```
     * SendContent.Attachments(
     *     attachments = listOf(
     *         SendAttachment.File(fileId = "123"),
     *         SendAttachment.Url(
     *              url = "https://example.com/image.jpg",
     *              fileName = "image.jpg"
     *         )
     *     )
     * )
     * ```
     */
    data class Attachments(
        val attachments: List<SendAttachment>
    ) : SendContent()


    /** Contact information to be sent in a message. */
    data class Contact(
        val name: String,
        val phone: String?,
        val email: String?
    ) : SendContent()


    /** Geographic location to be sent in a message. */
    data class Location(
        val name: String,
        val address: String,
        val latitude: Double,
        val longitude: Double
    ) : SendContent()


    /**
     * Message with combined content.
     *
     * Supports:
     * - text + attachments
     */
    data class Composite(
        val text: String,
        val attachments: List<SendAttachment> = emptyList()
    ) : SendContent()
}