package com.webitel.chat.sdk

/**
 * Represents message content received from the server.
 *
 * A message may include text, attachments, interactive elements (keyboard),
 * or a combination of these.
 *
 * Some fields (e.g. keyboard, system events) are server-driven and may not be
 * available when sending messages from the client.
 */
sealed class MessageContent {

    /** Plain text message. */
    data class Text(
        val text: String
    ) : MessageContent()


    /** Message containing only attachments. */
    data class Attachments(
        val attachments: List<MessageAttachment>
    ) : MessageContent()


    /**
     * Message containing only an interactive keyboard.
     *
     * Used for server-driven UI such as bots or quick replies.
     */
    data class KeyboardOnly(
        val keyboard: ChatKeyboard
    ) : MessageContent()


    /**
     * Message with combined content.
     *
     * Supports common combinations:
     * - text + attachments
     * - text + keyboard
     * - attachments + keyboard
     * - text + attachments + keyboard
     *
     * The keyboard field is typically populated by the server.
     */
    data class Composite(
        val text: String? = null,
        val attachments: List<MessageAttachment> = emptyList(),
        val keyboard: ChatKeyboard? = null
    ) : MessageContent()


    /** Contact information shared in a message. */
    data class Contact(
        val name: String,
        val phone: String?,
        val email: String?
    ) : MessageContent()


    /** Geographic location shared in a message. */
    data class Location(
        val name: String,
        val address: String,
        val latitude: Double,
        val longitude: Double
    ) : MessageContent()


    /**
     * System payload.
     *
     * Represents a non-user message generated by backend logic,
     * automation flows, integrations, or chat lifecycle events.
     *
     * Common built-in event types include:
     * - `member_added` – user joined the chat
     * - `member_removed` – user left the chat
     *
     * Additional event types may be defined by custom Flow schemas
     * and therefore should not be considered exhaustive.
     */
    data class System(
        /**
         * System event type.
         *
         * The value is defined by the backend and may represent either
         * a built-in chat event or a custom Flow event.
         *
         * Examples:
         * - `member_added`
         * - `member_removed`
         * - `order_status_changed`
         * - `ticket_closed`
         */
        val type: String,

        /**
         * Human-readable event description.
         *
         * Intended for displaying the event in the chat UI.
         */
        val text: String,

        /**
         * Optional event-specific metadata.
         *
         * The structure depends on the event type and is defined
         * by the backend or Flow schema.
         *
         * For built-in events this may contain predefined fields,
         * while custom Flow events can provide arbitrary values.
         *
         * Example:
         * {
         *   "userId": "123",
         *   "userName": "John Doe",
         *   "status": "approved"
         * }
         */
        val metadata: Map<String, Any>? = null
    ) : MessageContent()
}


/**
 * Represents message content that can be sent from the client.
 *
 * This is a restricted subset of [MessageContent].
 * The server may transform or extend the message after it is sent.
 */
sealed class SendContent {

    /** Plain text message. */
    data class Text(
        val text: String
    ) : SendContent()


    /**
     * Message containing one or more file attachments.
     *
     * Attachments may reference:
     * - previously uploaded files
     * - external URLs
     *
     * Example:
     * ```
     * SendContent.Attachments(
     *     attachments = listOf(
     *         SendAttachment.File(fileId = "123"),
     *         SendAttachment.Url(
     *              url = "https://example.com/image.jpg",
     *              fileName = "image.jpg"
     *         )
     *     )
     * )
     * ```
     */
    data class Attachments(
        val attachments: List<SendAttachment>
    ) : SendContent()


    /** Contact information to be sent in a message. */
    data class Contact(
        val name: String,
        val phone: String?,
        val email: String?
    ) : SendContent()


    /** Geographic location to be sent in a message. */
    data class Location(
        val name: String,
        val address: String,
        val latitude: Double,
        val longitude: Double
    ) : SendContent()


    /**
     * Message with combined content.
     *
     * Supports:
     * - text + attachments
     */
    data class Composite(
        val text: String,
        val attachments: List<SendAttachment> = emptyList()
    ) : SendContent()
}